version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: develop
    open-pull-requests-limit: 5
    groups:
      npm:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: develop

  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
      day: monday
    target-branch: develop

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: develop
    groups:
      actions:
        patterns: ["*"]
